name: alps2alps_test_task
description: "Alps2Alps test task."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter
  intl: any

  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  geolocator: ^13.0.3
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_maps_flutter: ^2.11.0
  injectable: ^2.5.0
  meta: ^1.15.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

flutter:
  generate: true
  uses-material-design: true
